parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: edudata
    database_user: root
    database_password: ''
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: srsx56bpeqs40wkg4ooos4okk0kkgcw
    user_partner: none